# Generated by Django 5.2.1 on 2025-12-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_age_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, choices=[('Indore', 'Indore'), ('Khargone', 'Khargone'), ('Bhopal', 'Bhopal'), ('Khandwa', 'Khandwa')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='condition',
            field=models.CharField(blank=True, choices=[('Diabetes', 'Diabetes'), ('Blood Pressure', 'Blood Pressure')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='has_condition',
            field=models.BooleanField(default=False),
        ),
    ]
